"""empty message

Revision ID: 37efb0c614db
Revises: 56d343dce482
Create Date: 2018-08-13 14:41:49.797168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37efb0c614db'
down_revision = '56d343dce482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Renter', sa.Column('currency', sa.String(length=30), nullable=True))
    op.add_column('Renter', sa.Column('nights', sa.Integer(), nullable=True))
    op.add_column('Renter', sa.Column('total_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Renter', 'total_cost')
    op.drop_column('Renter', 'nights')
    op.drop_column('Renter', 'currency')
    # ### end Alembic commands ###
