"""empty message

Revision ID: 3cae3295d6d7
Revises: 9770c91035ac
Create Date: 2018-08-10 09:54:03.369058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cae3295d6d7'
down_revision = '9770c91035ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Renter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.String(length=30), nullable=False),
    sa.Column('to_date', sa.String(length=30), nullable=False),
    sa.Column('bool_time', sa.Boolean(), nullable=True),
    sa.Column('from_time', sa.String(length=30), nullable=True),
    sa.Column('to_time', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['Property.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['Dir_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Data_system', 'system_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Data_system', 'system_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('Renter')
    # ### end Alembic commands ###
