"""empty message

Revision ID: 5dd585746faf
Revises: 962ffa0773d0
Create Date: 2018-08-17 10:09:34.211606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd585746faf'
down_revision = '962ffa0773d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuestInfo', sa.Column('system_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'GuestInfo', 'Dir_system', ['system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'GuestInfo', type_='foreignkey')
    op.drop_column('GuestInfo', 'system_id')
    # ### end Alembic commands ###
