"""empty message

Revision ID: 6bf7fe39c0d1
Revises: dd4213be0b6b
Create Date: 2018-07-30 18:54:02.337224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf7fe39c0d1'
down_revision = 'dd4213be0b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Property', sa.Column('flat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Property', 'Flat', ['flat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Property', type_='foreignkey')
    op.drop_column('Property', 'flat_id')
    # ### end Alembic commands ###
