"""empty message

Revision ID: 7504fd3aa64d
Revises: b19619d71107
Create Date: 2018-08-08 15:08:57.188920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7504fd3aa64d'
down_revision = 'b19619d71107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Photo', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Photo', 'Property', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Photo', type_='foreignkey')
    op.drop_column('Photo', 'property_id')
    # ### end Alembic commands ###
