"""empty message

Revision ID: 84b17f337d74
Revises: e6329c302bb7
Create Date: 2018-07-25 11:46:56.151284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b17f337d74'
down_revision = 'e6329c302bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dir_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('n_n_user_system',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['Dir_system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('n_n_user_system')
    op.drop_table('Dir_system')
    # ### end Alembic commands ###
