"""empty message

Revision ID: 8ae6ded6280f
Revises: 9c11bbc26417
Create Date: 2018-08-01 14:17:04.555475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae6ded6280f'
down_revision = '9c11bbc26417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Data_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('inner_user_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['Dir_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('n_n_user_system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('n_n_user_system',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['system_id'], [u'Dir_system.id'], name=u'n_n_user_system_system_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'User.id'], name=u'n_n_user_system_user_id_fkey')
    )
    op.drop_table('Data_system')
    # ### end Alembic commands ###
