"""empty message

Revision ID: 9770c91035ac
Revises: 7504fd3aa64d
Create Date: 2018-08-09 12:20:26.979575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9770c91035ac'
down_revision = '7504fd3aa64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calendar', sa.Column('system_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Calendar', 'Dir_system', ['system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Calendar', type_='foreignkey')
    op.drop_column('Calendar', 'system_id')
    # ### end Alembic commands ###
