"""empty message

Revision ID: b1584ffeb3e2
Revises: 37efb0c614db
Create Date: 2018-08-13 16:09:34.790783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1584ffeb3e2'
down_revision = '37efb0c614db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Data_system', sa.Column('name_slug', sa.String(length=120), nullable=True))
    op.drop_column('Data_system', 'inner_user_id')
    op.add_column('Property', sa.Column('number_of_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Property', 'number_of_guests')
    op.add_column('Data_system', sa.Column('inner_user_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Data_system', 'name_slug')
    # ### end Alembic commands ###
