"""empty message

Revision ID: bc47f85b39b0
Revises: 5dd585746faf
Create Date: 2018-08-17 10:17:14.329790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc47f85b39b0'
down_revision = '5dd585746faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('GuestInfo_system_id_fkey', 'GuestInfo', type_='foreignkey')
    op.drop_column('GuestInfo', 'system_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuestInfo', sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('GuestInfo_system_id_fkey', 'GuestInfo', 'Dir_system', ['system_id'], ['id'])
    # ### end Alembic commands ###
