"""empty message

Revision ID: cb8c1f5d14b8
Revises: bc47f85b39b0
Create Date: 2018-08-20 09:50:07.105642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8c1f5d14b8'
down_revision = 'bc47f85b39b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.String(length=30), nullable=True),
    sa.Column('to_date', sa.String(length=30), nullable=True),
    sa.Column('from_time', sa.String(length=30), nullable=True),
    sa.Column('to_time', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['Flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('GuestInfo', sa.Column('system_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuestInfo', 'system_id')
    op.drop_table('Rental')
    # ### end Alembic commands ###
