"""empty message

Revision ID: d36227df8da7
Revises: 84b17f337d74
Create Date: 2018-07-25 12:34:26.502265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36227df8da7'
down_revision = '84b17f337d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('n_n_user_system', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('n_n_user_system', 'token')
    # ### end Alembic commands ###
