"""empty message

Revision ID: d61bc289fe9e
Revises: b1584ffeb3e2
Create Date: 2018-08-14 10:25:12.728913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61bc289fe9e'
down_revision = 'b1584ffeb3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Renter', 'from_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Renter', 'guests',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Renter', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Renter', 'to_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Renter', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Renter', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Renter', 'to_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Renter', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Renter', 'guests',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Renter', 'from_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
