"""empty message

Revision ID: dc14cb33db11
Revises: f00f0461b96b
Create Date: 2018-08-02 18:53:45.292984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc14cb33db11'
down_revision = 'f00f0461b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flat', 'size')
    op.drop_column('Flat', 'city')
    op.drop_column('Flat', 'district')
    op.drop_column('Flat', 'country')
    op.drop_column('Flat', 'price')
    op.drop_column('Flat', 'min_stay')
    op.drop_column('Flat', 'currency')
    op.drop_column('Flat', 'photo_url')
    op.drop_column('Flat', 'zip_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flat', sa.Column('zip_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('currency', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('min_stay', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('district', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Flat', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
