"""empty message

Revision ID: dd4213be0b6b
Revises: e2c13ecd9127
Create Date: 2018-07-30 18:47:41.080254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4213be0b6b'
down_revision = 'e2c13ecd9127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=30), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('min_stay', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Property', sa.Column('currency', sa.String(length=30), nullable=True))
    op.add_column(u'Property', sa.Column('local_user_id', sa.Integer(), nullable=True))
    op.add_column(u'Property', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'Property', 'User', ['local_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Property', type_='foreignkey')
    op.drop_column(u'Property', 'photo_url')
    op.drop_column(u'Property', 'local_user_id')
    op.drop_column(u'Property', 'currency')
    op.drop_table('Flat')
    # ### end Alembic commands ###
