"""empty message

Revision ID: e6329c302bb7
Revises: ebde9099ec78
Create Date: 2018-07-24 14:36:11.420777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6329c302bb7'
down_revision = 'ebde9099ec78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('User', sa.Column('oauth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'oauth_token')
    op.drop_column('User', 'client_id')
    op.drop_table('Photo')
    # ### end Alembic commands ###
