"""empty message

Revision ID: ebde9099ec78
Revises: d9f4b8b07b2b
Create Date: 2018-07-23 16:18:16.850815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebde9099ec78'
down_revision = 'd9f4b8b07b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'auth_token')
    # ### end Alembic commands ###
