"""empty message

Revision ID: f00f0461b96b
Revises: 8ae6ded6280f
Create Date: 2018-08-01 14:49:54.179142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f0461b96b'
down_revision = '8ae6ded6280f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Data_system', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'Data_system_client_id_fkey', 'Data_system', type_='foreignkey')
    op.create_foreign_key(None, 'Data_system', 'User', ['user_id'], ['id'])
    op.drop_column('Data_system', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Data_system', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Data_system', type_='foreignkey')
    op.create_foreign_key(u'Data_system_client_id_fkey', 'Data_system', 'User', ['client_id'], ['id'])
    op.drop_column('Data_system', 'user_id')
    # ### end Alembic commands ###
